mydreamhouse/src/Entity/Ciudad.php
<?php

namespace App\Entity;

use App\Repository\CiudadRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CiudadRepository::class)
 */
class Ciudad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $nombre_ciudad;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreCiudad(): ?string
    {
        return $this->nombre_ciudad;
    }

    public function setNombreCiudad(string $nombre_ciudad): self
    {
        $this->nombre_ciudad = $nombre_ciudad;

        return $this;
    }

    public function __toString()
    {
        return $this->nombre_ciudad;
    }
}

mydreamhouse/src/Form/CiudadType.php
<?php

namespace App\Form;

use App\Entity\Ciudad;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CiudadType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre_ciudad')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ciudad::class,
        ]);
    }
}

mydreamhouse/src/Controller/CiudadController.php
<?php

namespace App\Controller;

use App\Entity\Ciudad;
use App\Form\CiudadType;
use App\Repository\CiudadRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ciudad")
 */
class CiudadController extends AbstractController
{
    /**
     * @Route("/", name="ciudad_index", methods={"GET"})
     */
    public function index(CiudadRepository $ciudadRepository): Response
    {
        return $this->render('ciudad/index.html.twig', [
            'ciudads' => $ciudadRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ciudad_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ciudad = new Ciudad();
        $form = $this->createForm(CiudadType::class, $ciudad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ciudad);
            $entityManager->flush();

            return $this->redirectToRoute('ciudad_index');
        }

        return $this->render('ciudad/new.html.twig', [
            'ciudad' => $ciudad,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ciudad_show", methods={"GET"})
     */
    public function show(Ciudad $ciudad): Response
    {
        return $this->render('ciudad/show.html.twig', [
            'ciudad' => $ciudad,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ciudad_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Ciudad $ciudad): Response
    {
        $form = $this->createForm(CiudadType::class, $ciudad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ciudad_index');
        }

        return $this->render('ciudad/edit.html.twig', [
            'ciudad' => $ciudad,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ciudad_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Ciudad $ciudad): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ciudad->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ciudad);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ciudad_index');
    }
}

mydreamhouse/templates/ciudad/_delete_form.html.twig
<form method="post" action="{{ path('ciudad_delete', {'id': ciudad.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ciudad.id) }}">
    <button class="btn">Delete</button>
</form>

mydreamhouse/templates/ciudad/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

mydreamhouse/templates/ciudad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ciudad{% endblock %}

{% block body %}
    <h1>Edit Ciudad</h1>

    {{ include('ciudad/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('ciudad_index') }}">back to list</a>

    {{ include('ciudad/_delete_form.html.twig') }}
{% endblock %}

mydreamhouse/templates/ciudad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ciudad index{% endblock %}

{% block body %}
    <h1>Ciudad index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre_ciudad</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ciudad in ciudads %}
            <tr>
                <td>{{ ciudad.id }}</td>
                <td>{{ ciudad.nombreCiudad }}</td>
                <td>
                    <a href="{{ path('ciudad_show', {'id': ciudad.id}) }}">show</a>
                    <a href="{{ path('ciudad_edit', {'id': ciudad.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('ciudad_new') }}">Create new</a>
{% endblock %}

mydreamhouse/templates/ciudad/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ciudad{% endblock %}

{% block body %}
    <h1>Create new Ciudad</h1>

    {{ include('ciudad/_form.html.twig') }}

    <a href="{{ path('ciudad_index') }}">back to list</a>
{% endblock %}

mydreamhouse/templates/ciudad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ciudad{% endblock %}

{% block body %}
    <h1>Ciudad</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ciudad.id }}</td>
            </tr>
            <tr>
                <th>Nombre_ciudad</th>
                <td>{{ ciudad.nombreCiudad }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('ciudad_index') }}">back to list</a>

    <a href="{{ path('ciudad_edit', {'id': ciudad.id}) }}">edit</a>

    {{ include('ciudad/_delete_form.html.twig') }}
{% endblock %}