mydreamhouse/src/Entity/Casa.php
<?php

namespace App\Entity;

use App\Repository\CasaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CasaRepository::class)
 */
class Casa
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $direccion;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=7, nullable=true)
     */
    private $tipo_venta;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $m2;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $precio;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $tipo_casa;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $propietario;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $email_casa;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $fecha_constr;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $imagen_casa;

    /**
     * @ORM\ManyToOne(targetEntity=Ciudad::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_ciu;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class)
     */
    private $id_usu;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getCp(): ?int
    {
        return $this->cp;
    }

    public function setCp(?int $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getTipoVenta(): ?string
    {
        return $this->tipo_venta;
    }

    public function setTipoVenta(?string $tipo_venta): self
    {
        $this->tipo_venta = $tipo_venta;

        return $this;
    }

    public function getM2(): ?int
    {
        return $this->m2;
    }

    public function setM2(?int $m2): self
    {
        $this->m2 = $m2;

        return $this;
    }

    public function getPrecio(): ?int
    {
        return $this->precio;
    }

    public function setPrecio(?int $precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    public function getTipoCasa(): ?string
    {
        return $this->tipo_casa;
    }

    public function setTipoCasa(?string $tipo_casa): self
    {
        $this->tipo_casa = $tipo_casa;

        return $this;
    }

    public function getPropietario(): ?string
    {
        return $this->propietario;
    }

    public function setPropietario(?string $propietario): self
    {
        $this->propietario = $propietario;

        return $this;
    }

    public function getTelefono(): ?int
    {
        return $this->telefono;
    }

    public function setTelefono(?int $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getEmailCasa(): ?string
    {
        return $this->email_casa;
    }

    public function setEmailCasa(?string $email_casa): self
    {
        $this->email_casa = $email_casa;

        return $this;
    }

    public function getFechaConstr(): ?int
    {
        return $this->fecha_constr;
    }

    public function setFechaConstr(?int $fecha_constr): self
    {
        $this->fecha_constr = $fecha_constr;

        return $this;
    }

    public function getImagenCasa(): ?string
    {
        return $this->imagen_casa;
    }

    public function setImagenCasa(?string $imagen_casa): self
    {
        $this->imagen_casa = $imagen_casa;

        return $this;
    }

    public function getIdCiu(): ?Ciudad
    {
        return $this->id_ciu;
    }

    public function setIdCiu(?Ciudad $id_ciu): self
    {
        $this->id_ciu = $id_ciu;

        return $this;
    }

    public function getIdUsu(): ?Usuario
    {
        return $this->id_usu;
    }

    public function setIdUsu(?Usuario $id_usu): self
    {
        $this->id_usu = $id_usu;

        return $this;
    }
}

mydreamhouse/src/Form/CasaType.php
<?php

namespace App\Form;

use App\Entity\Casa;
//use Doctrine\DBAL\Types\DateType;
//use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormTypeInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Validator\Constraints\File;

class CasaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('direccion', TextType::class)
            ->add('cp', NumberType::class)
            ->add('tipo_venta', ChoiceType::class, [
                'choices' => [
                    'Se vende' => 'Se vende',
                    'Se alquila' => 'Se alquila',
                ],
                'expanded' => true,
                'multiple' => false,
                'label' => 'Tipo de venta',
                'required' => true
            ])
            ->add('m2', NumberType::class)
            ->add('precio', NumberType::class)
            ->add('tipo_casa', ChoiceType::class, [
                'choices' => [
                    'Apartamento' => 'Apartamento',
                    'Ático' => 'Ático',
                    'Bajo' => 'Bajo',
                    'Duplex' => 'Duplex',
                    'Loft' => 'Loft',
                    'Chalet' => 'Chalet',
                    'Finca' => 'Finca'
                ],
                'expanded' => false,
                'multiple' => false,
                'label' => 'Tipo de casa',
                'required' => true
            ])
            ->add('propietario', NumberType::class)
            ->add('telefono', NumberType::class)
            ->add('email_casa', FileType::class, [
                'label' => 'Foto',
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '2048k',
                        'mimeTypes' => [
                            'image/png',
                            'image/jpeg',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => 'Por favor introduce un formato de imagen válido',
                    ])
                ],
            ])
            ->add('fecha_constr', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('imagen_casa', FileType::class, [
                'label' => 'Foto',
                'mapped' => false,
                'required' => true,
                'constraints' => [
                    new File([
                        'maxSize' => '2048k',
                        'mimeTypes' => [
                            'image/png',
                            'image/jpeg',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => 'Por favor introduce un formato de imagen válido',
                    ])
                ],
            ])
            ->add('id_ciu', EntityType::class, [
                'required' => true,
                'label' => 'Ciudad',
                'placeholder' => 'Selecciona ciudad...',
                'class' => 'App:Ciudad'
            ])
            /* ->add('id_usu') */;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Casa::class,
        ]);
    }
}

mydreamhouse/src/Controller/CasaController.php
<?php

namespace App\Controller;

use App\Entity\Casa;
use App\Form\CasaType;
use App\Repository\CasaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/casa")
 */
class CasaController extends AbstractController
{
    /**
     * @Route("/", name="casa_index", methods={"GET"})
     */
    public function index(CasaRepository $casaRepository): Response
    {
        return $this->render('casa/index.html.twig', [
            'casas' => $casaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="casa_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $casa = new Casa();
        $form = $this->createForm(CasaType::class, $casa);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($casa);
            $entityManager->flush();

            return $this->redirectToRoute('casa_index');
        }

        return $this->render('casa/new.html.twig', [
            'casa' => $casa,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="casa_show", methods={"GET"})
     */
    public function show(Casa $casa): Response
    {
        return $this->render('casa/show.html.twig', [
            'casa' => $casa,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="casa_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Casa $casa): Response
    {
        $form = $this->createForm(CasaType::class, $casa);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('casa_index');
        }

        return $this->render('casa/edit.html.twig', [
            'casa' => $casa,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="casa_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Casa $casa): Response
    {
        if ($this->isCsrfTokenValid('delete'.$casa->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($casa);
            $entityManager->flush();
        }

        return $this->redirectToRoute('casa_index');
    }
}

mydreamhouse/templates/casa/_delete_form.html.twig
<form method="post" action="{{ path('casa_delete', {'id': casa.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ casa.id) }}">
    <button class="btn">Delete</button>
</form>

mydreamhouse/templates/casa/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

mydreamhouse/templates/casa/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Casa{% endblock %}

{% block body %}
    <h1>Edit Casa</h1>

    {{ include('casa/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('casa_index') }}">back to list</a>

    {{ include('casa/_delete_form.html.twig') }}
{% endblock %}

mydreamhouse/templates/casa/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Casa index{% endblock %}

{% block body %}
    <h1>Casa index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Direccion</th>
                <th>Cp</th>
                <th>Tipo_venta</th>
                <th>M2</th>
                <th>Precio</th>
                <th>Tipo_casa</th>
                <th>Propietario</th>
                <th>Telefono</th>
                <th>Email_casa</th>
                <th>Fecha_constr</th>
                <th>Imagen_casa</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for casa in casas %}
            <tr>
                <td>{{ casa.id }}</td>
                <td>{{ casa.direccion }}</td>
                <td>{{ casa.cp }}</td>
                <td>{{ casa.tipoVenta }}</td>
                <td>{{ casa.m2 }}</td>
                <td>{{ casa.precio }}</td>
                <td>{{ casa.tipoCasa }}</td>
                <td>{{ casa.propietario }}</td>
                <td>{{ casa.telefono }}</td>
                <td>{{ casa.emailCasa }}</td>
                <td>{{ casa.fechaConstr }}</td>
                <td>{{ casa.imagenCasa }}</td>
                <td>
                    <a href="{{ path('casa_show', {'id': casa.id}) }}">show</a>
                    <a href="{{ path('casa_edit', {'id': casa.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('casa_new') }}">Create new</a>
{% endblock %}

mydreamhouse/templates/casa/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Casa{% endblock %}

{% block body %}
    <h1>Create new Casa</h1>

    {{ include('casa/_form.html.twig') }}

    <a href="{{ path('casa_index') }}">back to list</a>
{% endblock %}

mydreamhouse/templates/casa/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Casa{% endblock %}

{% block body %}
    <h1>Casa</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ casa.id }}</td>
            </tr>
            <tr>
                <th>Direccion</th>
                <td>{{ casa.direccion }}</td>
            </tr>
            <tr>
                <th>Cp</th>
                <td>{{ casa.cp }}</td>
            </tr>
            <tr>
                <th>Tipo_venta</th>
                <td>{{ casa.tipoVenta }}</td>
            </tr>
            <tr>
                <th>M2</th>
                <td>{{ casa.m2 }}</td>
            </tr>
            <tr>
                <th>Precio</th>
                <td>{{ casa.precio }}</td>
            </tr>
            <tr>
                <th>Tipo_casa</th>
                <td>{{ casa.tipoCasa }}</td>
            </tr>
            <tr>
                <th>Propietario</th>
                <td>{{ casa.propietario }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ casa.telefono }}</td>
            </tr>
            <tr>
                <th>Email_casa</th>
                <td>{{ casa.emailCasa }}</td>
            </tr>
            <tr>
                <th>Fecha_constr</th>
                <td>{{ casa.fechaConstr }}</td>
            </tr>
            <tr>
                <th>Imagen_casa</th>
                <td>{{ casa.imagenCasa }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('casa_index') }}">back to list</a>

    <a href="{{ path('casa_edit', {'id': casa.id}) }}">edit</a>

    {{ include('casa/_delete_form.html.twig') }}
{% endblock %}